resilience4j.circuitbreaker:
    instances:
        remoteService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 30s
            failureRateThreshold: 50