@startuml
skinparam BoxPadding 10
skinparam ParticipantPadding 20

actor User as U
box "Internal Service" #White
    participant ResilientController as RC
    participant ResilientService as RS
end box
box "External Service" #Red
    participant ExternalService as ES
end box

U -> RC: GET /remote
RC -> RS: remoteCall()
RS -> ES: remoteCall()
ES -> ES: compute
ES -> RS: RemoteCallResult
RS -> RC: RemoteCallResult
RC -> U: RemoteCallResult

@enduml